spring:
  datasource:
    druid:
      mall:
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://139.9.112.174:3306/mall?characterEncoding=utf8&serverTimezone=Asia/Shanghai
        # 数据源其他配置
        initialSize: 5
        minIdle: 5
        maxActive: 50
        maxWait: 900000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT CURRENT_DATE
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
      sky:
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://139.9.112.174:3306/sky?characterEncoding=utf8&serverTimezone=Asia/Shanghai
        # 数据源其他配置
        initialSize: 5
        minIdle: 5
        maxActive: 50
        maxWait: 900000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT CURRENT_DATE
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
logging:
  level:
    com.wcs.mall: DEBUG
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml